export const AppImages = {
  
  LOGO: require('../assets/images/food.jpg'),
  COMPANY_LOGO: require('../assets/images/company_logo.jpeg'),
  GOOGLE_LOGO: require('../assets/images/google_logo.png'),
  FACEBOOK_LOGO: require('../assets/images/facebook_logo.png'),
  APPLE_LOGO: require('../assets/images/Apple_Logo.png'),
  TICK: require('../assets/images/tick.png'),
  AVTAR:require('../assets/images/Avatar.png'),
  FACEGREEN:require('../assets/images/FaceGreen.png'),
  FACEYELLOW:require('../assets/images/FaceYellow.png'),
 BACK:require('../assets/images/BackBtn.png'),
 FGREEN:require('../assets/images/FingerGreen.png'),
 FGREY:require('../assets/images/FingerGrey.png'),
 CORNER_GREEN:require('../assets/images/CornerGreen.png'),
 CORNER_GREY:require('../assets/images/CornerGrey.png'),
  EDIT_ICON:require('../assets/images/Icon.png'),
  BASKET:require('../assets/images/BASKET.png'),
  LOC:require('../assets/images/LOC.png'),
  FAV:require('../assets/images/fav.png'),
  CROSS:require('../assets/images/cross.png'),
  MAP:require('../assets/images/map.png'),
  HEART:require('../assets/images/heart.png'),
  HOM:require('../assets/images/hom.png'),
  ORDER:require('../assets/images/clipboar.png'),
  FTRAY:require('../assets/images/healthy-food.png'),
  NOT:require('../assets/images/notification.png'),
  USE:require('../assets/images/us.png')
};
