export const AppColors = {
  PRIMARY_BACKGROUND: '#FFFFFF',
  GRADIENT_BACKGROUND: '#FF6347',
  COUNTRY_BACKGROUND: '#E9EAEB',

  WHITE_TEXT: '#FFFFFF',
  CODE_TEXT: '#697079',
  NUMBER_TEXT: '#0D1217',

  CHECKBOX_BORDER: '#647ea0ff',
  LINE_COLOR: '#6D6C69',

  LOADER: '#57595B',

  TRANSPARENT: 'transparent',
};
